### ISSUE TITLE
Connection/Disconnection Loop 

### ISSUE THREAD

**Issue by Henri75** [apohl79/audiogridder#1051] opened 2022-10-09 21:51 UTC
So I did my homework with tracing enable, and I can provide you with full logs with tracing enabled on two cases :

1. First is on a project where every time I open it a plugin is not loaded (AG status stays in orange). What is weird is that if I disconnect/reconnect most of the times it loads the plugin blazingly  fast ! So clearly a connection issue. In this case this is a 100% reproductible every time I open this project (the plugin which doesn’t load at first is Needlepoint) 

3. Second case is the typical connection loop issue. It seems to happen more frequently when I switch between servers. Here is the typical case : I add an AG insert, change the server and it is unable to connect to that new server (connection/disconnection loop). If I try to disconnect/reconnect several times it may finally connect or not, even if I have already a lot of AG inserts working perfectly with that server. Where it gets weird is that I remove the AG insert, I add a new one which then instantly connect to that server (AG connects to the last used server) !  Yes the same server that I was unable to connect with the blank AG plugin before.   

I added a screenshot showing too both issues on the AG monitoring.

Let me know if you need help to test a fix.

I hope that will help you to fix that long lasting issue for good, which makes AG hard to use for now. 
Which is a pity because when AG works it is amazing !
![Screen Shot 2022-10-09 at 23 42 18](https://user-images.githubusercontent.com/56123216/194780758-2c654597-d5ae-4d34-8107-23e27e9ae26f.png)

[Connection Loop Client.zip](https://github.com/apohl79/audiogridder/files/9742614/Connection.Loop.Client.zip)
[NeedlePoint Client.zip](https://github.com/apohl79/audiogridder/files/9742615/NeedlePoint.Client.zip)

[Connection Loop Server.zip](https://github.com/apohl79/audiogridder/files/9742617/Connection.Loop.Server.zip)
[NeedlePoint Client 2.zip](https://github.com/apohl79/audiogridder/files/9742618/NeedlePoint.Client.2.zip)

![Screen Shot 2022-10-09 at 23 40 19](https://user-images.githubusercontent.com/56123216/194780716-2ff1ec17-449c-4659-8aae-eaa671b03b76.png)

_Originally posted by @Henri75 in https://github.com/apohl79/audiogridder/discussions/603#discussioncomment-3835056_

**Comment by apohl79** [comment] 2022-10-12 08:24
It looks like the sandboxes are immediately shutting down after starting, when this loop is happening, because if they would crash, the log file would still be there. But for all looping plugins, that I found, I can't find any server log. So maybe the sandbox is not able to bind to a port. Not sure. So, can I ask you for the following:

The auto cleanup of sandbox logfiles at a clean shutdown can be disabled by opening the server config at `~/.audiogridder/audiogridderserver.cfg` and changing

```
    "SandboxLogAutoclean": true,
```
to
```
    "SandboxLogAutoclean": false,
```
After this, could you load your looping session and send me the server log folder again (I need the `Server` and the `Sandbox-Chain` directories)?

Thx!!

**Comment by apohl79** [comment] 2022-10-12 08:43
Regarding Needle, none of the server logs contains a load attempt. When you load the session, loading needle times out (the default is 15 seconds). If you can send me the logs of your thinkpad server, I might be able to see whats going on and if if it finally loads. The timeout can be increased manually via plugin config file, see `LoadPluginTimeoutMS`.

**Comment by apohl79** [comment] 2022-10-12 18:00
Quick question (trying to confirm a theory): If you enable the "bypass when not ready" setting in the plugin and reload the session, do you still have the connection loop?

<img width="409" alt="image" src="https://user-images.githubusercontent.com/1129160/195415064-3ffad29c-9c38-4f9c-92d4-2815d20b603b.png">

**Comment by Henri75** [comment] 2022-10-12 20:31
I just made a quick test : it seems to connect (first impression not as
fast, as it if hangs for a couple of seconds) then it connects without
problem !

I guess you have found the issue :)

By the way what is the use of :
- bypass when not ready
- and realtime mode ?



Le mer. 12 oct. 2022 à 20:00, Andreas Pohl ***@***.***> a
écrit :

**Comment by apohl79** [comment] 2022-10-13 07:39
Thats great! Thanks for the logs and traces!

> By the way what is the use of :
> - bypass when not ready

When the plugin is not connected to the server or there is a problem loading the plugin chain, it will bypass itself and leave the audio processing routine very early.

> - and realtime mode ?

Sets strict internal processing timeouts required for realtime processing of audio data. If those timeouts are not met, AG will drop audio internally to avoid blocking the DAW. If you do (offline) bouncing, you should deactivate this.

**Comment by Henri75** [comment] 2022-10-13 08:21
thanks for the details.

I guess you have found the issue :)

By the way, please think to add track name support for Studio One ! It is a
mess when you use a lot of AG insert and have no name in the monitor ...



Le jeu. 13 oct. 2022 à 09:40, Andreas Pohl ***@***.***> a
écrit :

**Comment by apohl79** [comment] 2022-10-13 08:31
> I guess you have found the issue :)

Yes, it seems that the plugin was running into audio timeouts at initialization time. The bypass setting was avoiding this as you confirmed. So I can add a fix for this, when this setting is deactivated.

> please think to add track name support for Studio One

I have a feature request for this on the list. But I will not add this for v1.2 as I just want to get it stable right now (and I think I'm very close).

The problem is, that presonus decided to add a VST3 extension for this, instead of using standard VST3 features. This means I have to merge the presonus fork of JUCE into the AG fork of JUCE and maintain it, which is not great!

**Closed** 2022-10-15 22:47 UTC
Labels: bug
