### ISSUE TITLE
Beta 5 hangs Cubase

### ISSUE THREAD

**Issue by igbro** [apohl79/audiogridder#153] opened 2020-09-30 10:22 UTC
Hallo Andreas, after upgrading to beta 5 (on both sides of course), when I load a previous project made with a bunch (15) of AG vst2 plugins, Cubase hangs when attempting to open any AudioGridder instance.
No AG Vts2 plugin UI opens and Cubase freezes. (Busy wheel keeps turning)
Server is not crashing.

I tried with a blank project, (only one AG plugin instance) vst2 UI opens and I'm able to load a server plugin inside but Cubase hangs when closing the project (maybe at the time it unloads the AG instance)

All W7 here (maybe the culprit) and last Cubase 10.5. Everything was fine with beta 4. 
I use vst2 AG because it seemed more stable in my system.

**Comment by henride** [comment] 2020-09-30 11:06
Same here .... W10 Cubase 10.5 VST3.

**Comment by apohl79** [comment] 2020-09-30 11:59
ok thx, will try to reproduce this

**Comment by audiokrat** [comment] 2020-09-30 21:04
same here:
AudioInst VST2 crashes Cubase, Ableton Live, Element on Mac 10.14.6
beta4 and beta5 - beta3 was fine

**Comment by apohl79** [comment] 2020-09-30 21:07
Can you provide the crash report?

**Comment by audiokrat** [comment] 2020-09-30 21:11
I have just created a Live crash report by inserting into a new set. I'd rather send via PM than post it here...

**Comment by apohl79** [comment] 2020-10-01 06:45
you can mail me under audiogridder at e47.org

**Comment by igbro** [comment] 2020-10-02 14:37
Hallo Andreas, same with beta 6 with the same project (working perfectly with beta 4).

Cubase hangs when opening any AG instance.
Bound to kill Cubase, maybe you can see it in the server log, but server doesn't crash.
Plug doesn't add info in its log when it hangs cubase (I suppose plugin is crashing)
Here are my logs, hope it helps:

[AudioGridderPlugin_2020-10-02_16-24-36.log](https://github.com/apohl79/audiogridder/files/5318528/AudioGridderPlugin_2020-10-02_16-24-36.log)
[AudioGridderServer_2020-10-02_16-23-58.log](https://github.com/apohl79/audiogridder/files/5318533/AudioGridderServer_2020-10-02_16-23-58.log)

**Comment by igbro** [comment] 2020-10-02 14:50
Here a the logs with the same project working in beta 4.
Maybe comparing helps.

[AudioGridderServer_2020-10-02_16-41-39.log](https://github.com/apohl79/audiogridder/files/5318665/AudioGridderServer_2020-10-02_16-41-39.log)

[AudioGridderPlugin_2020-10-02_16-42-02.log](https://github.com/apohl79/audiogridder/files/5318662/AudioGridderPlugin_2020-10-02_16-42-02.log)

**Comment by apohl79** [comment] 2020-10-02 14:55
thx a lot, will have a look!

**Comment by apohl79** [comment] 2020-10-02 16:13
I don't see anything strange in the logs, no errors. And the problem is, I don't have any issues with cubase on OSX.

Just to understand where exactly it hangs: 

So you can load the project, and it hangs when opening an AG plugin? Or when you click on the remote plugin in AG to start the screen capturing?
And before it hangs, does CB load the entire project? And can you start the playback?

Do you ever get it working with beta6? Or does it never work?

Thx for helping debug this!

**Comment by henride** [comment] 2020-10-02 16:38
Hi Andreas 

I can load the project. If I will open the plugin container (by clicking on it e.g. in the mix console) Cubase stops.
No plugin window is show. It is a step before start capturing. It happens while open the plugin window

Same in beta6. No changes.

**Comment by igbro** [comment] 2020-10-02 16:50
Project loads and plays but opening AG plugin freezes the DAW, before asking for screen capturing.
Vst2 AG instances here.

Seems to crash at plugin level side since server remains running.

Got that since beta 5 (so 6 too), beta 4 fully working.
Same for @henride who is running W10 and vst3 instances (I run W7 on both machines)

Here is a video.
    Le vendredi 2 octobre 2020 à 18:13:49 UTC+2, Andreas Pohl <notifications@github.com> a écrit :  
 
 


I don't see anything strange in the logs, no errors. And the problem is, I don't have any issues with cubase on OSX.

Just to understand where exactly it hangs:

So you can load the project, and it hangs when opening an AG plugin? Or when you click on the remote plugin in AG to start the screen capturing?
And before it hangs, does CB load the entire project? And can you start the playback?

Do you ever get it working with beta6? Or does it never work?

Thx for helping debug this!

**Comment by apohl79** [comment] 2020-10-02 17:48
ok thank you guys! that reduces the problem area! will hopefully find the problem soon!

**Comment by apohl79** [comment] 2020-10-04 11:39
I added more logging and a few fixes and locking changes in beta7. It is hopefully solving this issue or at least provide more info about its root cause.

**Comment by igbro** [comment] 2020-10-04 12:41
Also seems to be fixed for me with beta7! 
Ag plugin instances open now.

**Comment by henride** [comment] 2020-10-04 13:09
Hi Andreas,

tried beta7. Before I was on beta3.

Cubase freezed at least. Couldn't play any sound.
Find my logs attached. I hope it helps.

[AudioGridderFX.zip](https://github.com/apohl79/audiogridder/files/5323252/AudioGridderFX.zip)

**Comment by audiokrat** [comment] 2020-10-06 09:40
> same here:
> AudioInst VST2 crashes Cubase, Ableton Live, Element on Mac 10.14.6
> beta4 and beta5 - beta3 was fine

Fixed for me. with Beta7. Thank you! :))

**Comment by apohl79** [comment] 2020-10-09 10:45
> Hi Andreas,
> 
> tried beta7. Before I was on beta3.
> 
> Cubase freezed at least. Couldn't play any sound.
> Find my logs attached. I hope it helps.
> 
> [AudioGridderFX.zip](https://github.com/apohl79/audiogridder/files/5323252/AudioGridderFX.zip)

I can't get enough data from the logs. The next beta will have tracing capabilities. I will close this issue now. Please open a new issue if the problem persists with the next version and tracing enabled, so I can hopefully figure out, what the problem is. thx!

**Closed by apohl79** 2020-10-09 10:45 UTC
Labels: bug
