### ISSUE TITLE
Resizing plugin widow tends to crash Audiogridder server (freeze)

### ISSUE THREAD

**Issue by lorenzolamasse** [apohl79/audiogridder#138] opened 2020-09-10 13:31 UTC
On 1.1beta1, client is OSX 10.4.8, Logic Pro 10.5.1, server is Win10, using MPowerfactory from Melda.
The issue is that most Melda plugins first tend to open popups for various things (presets management, wavetables edition, ...), these popup often being outside the plugin window and not detected by audiogridder. Thus I resize the plugin window so the pop ups are inside it (bottom right handle). It works quite well, but tends to freeze Audiogridder and I have no other way than killing the process after that. Sometimes it goes to freezing the client host.

**Comment by apohl79** [comment] 2020-09-11 07:05
If you see problems/crashes etc, please follow these steps to provide enough info:

https://github.com/apohl79/audiogridder#reporting-of-bugsissues

thx

**Comment by lorenzolamasse** [comment] 2020-09-11 08:31
There you go. 

I actually have a systematic freeze of Audiogridder server when resizing Melda plugin more than once or twice.
See attached report logs
[AudioGridderServer.zip](https://github.com/apohl79/audiogridder/files/5207669/AudioGridderServer.zip)

**Comment by apohl79** [comment] 2020-09-11 15:10
Can you try beta3?

**Comment by lorenzolamasse** [comment] 2020-09-11 15:19
Same, audiogridder get stuck after two or three resizes, and then Windows asks for killing it.

 

Here is the new log

 

From: Andreas Pohl <notificat :ions@github.com>
Reply to: apohl79/audiogridder <reply@reply.github.com>
Date: Friday 11 September 2020 at 17:10
To: apohl79/audiogridder <audiogridder@noreply.github.com>
Cc: lorenzolamasse <lorenzolamasse@catlover.com>, Author <author@noreply.github.com>
Subject: Re: [apohl79/audiogridder] Resizing plugin widow tends to crash Audiogridder server (freeze) (#138)

 

Can you try beta3?

**Comment by apohl79** [comment] 2020-09-14 13:49
Looks like it is more tricky to reproduce this than I expected. Still no luck to get the server to die, no matter how many times I switch between plugins or resizing the capture area. Could you capture a video showing the behaviour by any chance?

**Comment by apohl79** [comment] 2020-09-14 13:52
duplicate issue, closing this one. #141

**Closed by apohl79** 2020-09-14 13:52 UTC

**Comment by lorenzolamasse** [comment] 2020-09-14 14:36
There you go: https://we.tl/t-o0owq5XwyH

**Comment by apohl79** [comment] 2020-09-14 14:48
thx a mill
