### ISSUE TITLE
speed question

### ISSUE THREAD

**Issue by emerymastering** [apohl79/audiogridder#134] opened 2020-09-09 09:20 UTC
Wondering if using 2 network cards, on server and client side, and splitting the traffic would result in faster response and less audio stuttering when tweaking AA plugins? Because now in maximum buffer size 2048 in Nuendo and 186 ms in Agridder I get audio stuttering once tweaking AA plugins parameters. Then after tweaking all plays normal again, but i had 2 cases already with stuttering rendered in final masters.

What do you think Andreas? What is the bottleneck in this case? Ethernet or something else?

Cheers
Denis

**Comment by apohl79** [comment] 2020-09-09 21:51
You will have to increase the buffer size in AG. You might have to use rather high values with many channels in your session. For me things usually get shaky with +25 channels or so. Probably different in different environments (depending on the network HW, other users on your network etc).

The problem is (or at least part of it), that the audio data is transferred using TCP currently. This is not optimal for real-time applications. I started to work on implementing RTP transfer, but it's a lot of work and will take a while. Also as the number of feature requests grows pretty fast right now. :-)

**Comment by emerymastering** [comment] 2020-09-10 07:27
nice, RTP sounds promising!:) I have like 3 instances of AG in a project, with 2 instances having 1 AA plugin and other instance has 3 AA plugins. They are quite heavy plugins: Scarlett, Taupe, Pensado EQ, Celestial.
So yeah looking forwards to RTP development, ready to support it with another donation!
Cheers
Denis

**Closed** 2021-02-04 19:15 UTC
